apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapweb-deployment
  labels:
    app: kapweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kapweb
  template:
    metadata:
      labels:
        app: kapweb
    spec:
      containers:
      - name: kapweb
        image: kapwebsite-kapweb:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "pswJardineria"
        - name: DB_HOST
          value: "kapdb"
        - name: DB_PORT
          value: "5432"
