apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapdb-deployment
  labels:
    app: kapdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapdb
  template:
    metadata:
      labels:
        app: kapdb
    spec:
      containers:
      - name: kapdb
        image: kapwebsite-db:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "pswJardineria"
        - name: POSTGRES_DB
          value: "Jardineria"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
