CONTEXTO=/home/kevin/examenrecu
IDRSA=kapclaves/kapid_rsa.pub
APP=kapwebsite
REPO=https://github.com/morgadodesarrollador/ApiJardineriaNest.git
DOCKERFILE_TALLER=./kapdockerfile/kapwebsite
DOCKERFILE_datos=./kapdockerfile/kapbasededatos
AUTOCARAVANEANDO_DIR=./kapproyectos/kapwebsite
LOG=/root/logs/logs.txt
PORT=9001
INICIALES=kap
# DB_HOST=91.229.245.2
DB_HOST=172.220.10.3
DB_PORT=5433
DB_USERNAME=postgres
DB_NAME=Jardineria
DB_PASSWORD=pswJardineria
PORT=3000
HOST_API=http://localhost:3000/api
JWT_SECRET=MIclaveSecreta1